#!/usr/bin/env bash
# To installs nginx and configures it.

sudo apt-get -y update
sudo apt-get -y install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -C "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo service nginx start
