#!/usr/bin/env bash
# Install and configure HAproxy:

sudo apt-get -y update
sudo apt-get -y install haproxy

echo '
frontend infront
        bind 0:80
		default_backend server_back

backend server_back
        balance roundrobin
        server 381561-web-01 52.90.14.193:80 check
        server 381561-web-02 54.90.50.39:80 check
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
