#!/usr/bin/env bash
# Install and configure HAproxy:

# the package list
sudo apt-get -y update

#install
sudo apt-get -y install software-properties-common

# the HAProxy
sudo add-apt reporsitory -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

# Confugure haproxy
balance="/
frontend haproxy_balancer
    blace roundrobin
    server
    server
"

# add the hyproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo /etc/haproxy/haproxy.cfg{,.orig}

sudo service haproxy start
