#!/usr/bin/env bash
# Script For the infinity and beyond infinetly.
# Sleep 2 in between iteration.
#  am ivincible !!

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
