#!/usr/bin/env bash
# Script :Parses Apache log files in 'list format'.
#  Groups of visitors by IP and HTTP status code.
#  Displays that number of occurrences, IP, and HTTP status
# Code of each log, in sorted order.

awk '{ print$1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
