#!/usr/bin/env bash
# a script that loops from 1 to 10
# displays bad luck for the 4th loop iteration
# Must use while loop, if, elif and else statement

i=1
while [ $i -lt 11 ];
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
