#!/usr/bin/env bash
# Script for the loops 'from 1 to 20'

index=0
number=1

while [ $index -lt 20 ]
do
  echo $number
  case $index in
    3)
       echo "bad luck from China";;
    8)
       echo "bad luck from Japan";;
    16)
       echo "bad luck from Italy"
  esac
  ((index++))
  ((number++))
done
