#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx stop
echo 'user nginx;' >> /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
